name: CI/CD
on:
  push:
    branches:
      - dev
      - release
      - master

jobs:
  job_one:
    name: Build Task
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'build') }}
    steps:
      - name: Echo Time Stamp
        run: |
          echo $(date --date="now +8 hours" +%Y-%m-%d%t%H:%M:%S)

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Task
        run: tar -czvf dist.tar ./src ./koa* ./http-error ./cookies ./request-body ./package.json ./pm2.config.js

      - name: Sign In Remote Server
        uses: D3rHase/ssh-command-action@v0.2.1
        with:
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          # 依次执行多个 command，中间使用分号 “;” 隔开
          COMMAND: |
            cd /root/workspace/aitweb-back-end;
            npm run stop:server;
            rm -rf dist.tar ./src ./koa* ./http-error ./cookies ./request-body;
            exit;

      - name: Upload Code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: dist.tar
          target: /root/workspace/aitweb-back-end

      - name: Reload Remote Server
        uses: D3rHase/ssh-command-action@v0.2.1
        with:
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          # 依次执行多个 command，中间使用分号 “;” 隔开
          COMMAND: |
            cd /root/workspace/aitweb-back-end;
            tar -xzvf ./dist.tar;
            npm i;
            npm run start:server;
            exit;


  # job_two:
  #   name: Sign In Remote Server
  #   runs-on: ubuntu-latest
  #   needs: [job_one]
  #   if: ${{ startsWith(github.event.head_commit.message, 'build') }}
  #   steps:
  #     - name: Uzip File
  #       uses: D3rHase/ssh-command-action@v0.2.1
  #       with:
  #         HOST: ${{secrets.HOST}}
  #         PORT: ${{secrets.PORT}}
  #         USER: ${{secrets.USER}}
  #         PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
  #         # 依次执行多个 command，中间使用分号 “;” 隔开
  #         COMMAND: |
  #           cd /root/workspace/aitweb-back-end;
  #           rm -rf dist.tar ./src ./koa* ./http-error ./cookies ./request-body;
  #           tar -xzvf ./dist.tar;
  #           npm i;
  #           npm run stop:server;
  #           npm run start:server;
