name: CI/CD
on:
  push:
    branches:
      - dev
      - release
      - master

jobs:
  job_one:
    name: Build Task
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'build') }}
    steps:
      - name: Echo Time Stamp
        run: |
          echo $(date --date="now +8 hours" +%Y-%m-%d%t%H:%M:%S)

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Task
        run: tar -czvf dist.tar ./src ./koa* ./http-error ./cookies ./request-body ./package.json

      - name: Upload Code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: dist.tar
          target: /root/workspace/aitweb-back-end

  job_two:
    name: Sign In Remote Server
    runs-on: ubuntu-latest
    needs: [job_one]
    if: ${{ startsWith(github.event.head_commit.message, 'build') }}
    steps:
      - name: Sign In Server
        uses: D3rHase/ssh-command-action
        with:
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          USER: ${{secrets.USER}}
          PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
          COMMAND: ${ cd /root/spacework/aitweb-back-end; tar -xzvf dist.tar }
